### ISSUE TITLE
How to install this skin?

### ISSUE THREAD

**Issue by gamebrew-org** [neayi/skin-neayi#12]
Love your skin.

Is there any guide or tutorial on how to installing this theme?

Cheers,

**Comment by bertrandgorge** [comment]
Hi, thanks. It's based on https://www.mediawiki.org/wiki/Skin:Chameleon - but it also requires a bunch of extensions (such as https://github.com/neayi/mw-NeayiNavbar) to fix in JS what can't be fixed through the skin itself (basically I go as far as I can with the skin and Chameleon, and then I finish up with some JS at display time).

You can have a look at the LocalConfig file here if you are stuck with the setup itself: https://github.com/neayi/tripleperformance/blob/main/config/LocalSettings.php#L345
